### ISSUE TITLE
How to use this script? Is it for decryption of files encrypted by GandCrab?

### ISSUE THREAD

**Issue by ing-norante** [laciKE/gandcrab_string_decryptor#1]
Hello, forgive me for this silly questions but a colleague of mine got infected by GrandCrab 5.2 and I was eager to help him. 

This is what I did: 

Downloaded IDA64 for Mac, opened an infected file (extension .qxaamcgv) it asks me to choose an entry point but I have no idea what to choose. From the File menu, I've imported the .idc script from your repository in the snippet list and when I run it I just get "=====GandCrab String Decryptor=====" in the Output window. 

Am I completely getting wrong the nature of your script? 

Any help would be very appreciated, even just to point me in the right direction! 

Cheers,
Giuseppe

**Comment by laciKE** [comment]
Hello Giuseppe

Unfortunately, my script is helper tool for malware analysts and its purpose is to decrypt some internal GandCrab stuff (text strings, like ransom note are placed in GandCrab code in some unreadable manner). But currently there is no decryptor for files encrypted by GandCrab v5.2, only for GandCrab v5.1.

I recommend you to backup your encrypted files and ransom note, it is very likely that in near future there will be available decryptor also for v5.2. Follow the Twitter, tech news or watch the [https://www.nomoreransom.org](https://www.nomoreransom.org)

And few words about IDA, it is the disassembler, which means its purpose is to "convert" binary executable files to the assembly instructions (low level programming language). For example, if you have access to the original ransomware executable (like .exe file on Windows, but not the encrypted data files produced by GandCrab), you can see its code. Some parts of it are obfuscated (like strings), and my script helps with their deobfuscation. 

Thanks for your question, it can be helpful also for another people.

Best regards

lacike

**Comment by ing-norante** [comment]
Thank you very much for this clarification! I'll follow your advice hoping to get a 5.2 decryptor soon. 
Cheers!
